### ISSUE TITLE
call to closeAfterDark

### ISSUE THREAD

**Issue by chuckster53** [srmooney/SmartThings#1]
Looking at the code I found that the API runOnce had a typo "runonce" and also I initialized now and after doing so no longer get an exception.   Here is the new code

```
    def now = new Date()
     /*
    log.debug "nowTime: $now"
    runonce(now + closeAfter, closeWhenDark)
    */
    runOnce(now + closeAfter, closeWhenDark)
```

**Comment by srmooney** [comment]
Thanks for finding that, I have fixed and updated the file

**Comment by chuckster53** [comment]
I cloned your code (see GarageDoorMgmt) and made a number of changes in for my environment.  I have a tilt sensor to monitor the garage door and a RM10 relay and appliance module.   Been doing a lot of testing and think one of the next changes is to send a warning before closing the garage door as doing an unmonitored garage door closing is a bit worrisome.
